### ISSUE TITLE
qUINT dependency

### ISSUE THREAD

**Issue by martymcmodding** [aestheticses/shaders-reshade#1]
I'd really recommend using ReShade.fxh instead of qUINT_common.fxh (I see you've used ADOF as template) as I change things often in the include file, which will break your things. It's the only reason I have my own include, so I'm not surprised by foreign changes. Also, **please don't hijack my project name like this** , make your own stuff, thanks.

**Comment by aestheticses** [comment]
> I'd really recommend using ReShade.fxh instead of qUINT_common.fxh (I see you've used ADOF as template) as I change things often in the include file, which will break your things. It's the only reason I have my own include, so I'm not surprised by foreign changes. Also, **please don't hijack my project name like this** , make your own stuff, thanks.

Sorry, and Thanks for reminding me. I have changed the dependency.
